### ISSUE TITLE
Aarch64 edition cannot see video stream of h265 file

### ISSUE THREAD

**Issue by odlg** [flathub/org.kde.kdenlive#521]
It seems that h265/hevc is not available. 

Doing `ffmpeg -encoders` outputs [ffmeg.encoders.txt](https://github.com/user-attachments/files/19191905/ffmeg.encoders.txt)
Doing `ffmpeg -decoders` outputs [ffmeg.decoders.txt](https://github.com/user-attachments/files/19191961/ffmeg.decoders.txt)
Doing `ffmpeg -encoders  > ffmeg.txt 2>&1` outputs  [ffmeg.txt](https://github.com/user-attachments/files/19191998/ffmeg.txt)

**Comment by Erick555** [comment]
You must call `/app/bin/ffmpeg -encoders`.

**Comment by odlg** [comment]
On aarch64 there are significantly fewer files that on x86_64. Here is a list of the ones that are there:

```
[📦 org.kde.kdenlive ~]$ ls -l /app/bin
total 13860
-rwxr-xr-x. 2 nfsnobody nfsnobody   269184 jan  1  1970 dvdauthor
-rwxr-xr-x. 2 nfsnobody nfsnobody      880 jan  1  1970 dvddirdel
-rwxr-xr-x. 2 nfsnobody nfsnobody   200600 jan  1  1970 dvdunauthor
-rwxr-xr-x. 4 nfsnobody nfsnobody   133688 jan  1  1970 flexiblas
-rwxr-xr-x. 2 nfsnobody nfsnobody 12470008 jan  1  1970 kdenlive
-rwxr-xr-x. 2 nfsnobody nfsnobody   136480 jan  1  1970 kdenlive_render
-rwxr-xr-x. 2 nfsnobody nfsnobody    69904 jan  1  1970 mediainfo
-rwxr-xr-x. 2 nfsnobody nfsnobody    69304 jan  1  1970 melt-7
lrwxrwxrwx. 1 nfsnobody nfsnobody        6 mar 11 11:55 mlt-melt -> melt-7
-rwxr-xr-x. 2 nfsnobody nfsnobody   200368 jan  1  1970 mpeg2desc
lrwxrwxrwx. 1 nfsnobody nfsnobody        3 mar 11 11:55 play -> sox
lrwxrwxrwx. 1 nfsnobody nfsnobody        3 mar 11 11:55 rec -> sox
-rwxr-xr-x. 2 nfsnobody nfsnobody   201040 jan  1  1970 sox
lrwxrwxrwx. 1 nfsnobody nfsnobody        3 mar 11 11:55 soxi -> sox
-rwxr-xr-x. 2 nfsnobody nfsnobody   203448 jan  1  1970 spumux
-rwxr-xr-x. 2 nfsnobody nfsnobody   200464 jan  1  1970 spuunmux
[📦 org.kde.kdenlive ~]$ 
```
So guess it is using the system ffmpeg?

**Comment by odlg** [comment]
The output is

```
Kdenlive - Video editor

          ID: org.kde.kdenlive
         Ref: app/org.kde.kdenlive/aarch64/stable
        Arch: aarch64
      Branch: stable
     Version: 24.12.2
     License: GPL-3.0-only
      Origin: fedora
  Collection: 
Installation: system
   Installed: 238,1 MB
     Runtime: org.fedoraproject.KDE6Platform/aarch64/f41
         Sdk: org.fedoraproject.KDE6Sdk/aarch64/f41

      Commit: d8af8060c7baceeeeafd980029e9917d7dcf989dcb2a47da45feef45c0ca3ade
     Subject: Export org.kde.kdenlive
        Date: 2025-02-11 20:41:37 +0000
      Alt-id: 5016501321fa294346732fb7f92158a9a2609d8ebd9c3e887ac5988504fb0da6
```
This is from a fedora flatpak repo. Installing kdenlive from flathub repo makes h265 work. It works now, thanks.
